(ns app.temp-db)

(def latest-launch {:spacex/latest-launch {:spacex.launch/flight-number             83,
                                           :spacex.launch.links/wikipedia           "https://en.wikipedia.org/wiki/Spacecom",
                                           :spacex.rocket/rocket-type               "FT",
                                           :spacex.launch-pad/site-id               "ccafs_slc_40",
                                           :spacex.launch/mission-id                [],
                                           :spacex.launch.links/video-link          "https://youtu.be/fZh82-WcCuo",
                                           :spacex.launch-pad/site-name-long        "Cape Canaveral Air Force Station Space Launch Complex 40",
                                           :spacex.launch/details                   "SpaceX will launch Boeing built Amos-17, a geostationary communications satellite for Israeli company Spacecom. The satellite will be delivered to GTO from KSC LC-39A or possibly CCAFS SLC-40, and will replace the defunct Amos-5 at 17° E. Amos-17 carries multi-band high throughput and regional beams servicing Africa, Europe and the Middle East. The cost of this launch is covered for Spacecom by SpaceX credit following the Amos-6 incident. A recovery of the booster for this mission is not expected.",
                                           :spacex.launch.fairings/ship             "GOMSTREE",
                                           :spacex.launch.links/mission-patch       "https://images2.imgbox.com/a0/ab/XUoByiuR_o.png",
                                           :spacex.launch/launch-window             5280,
                                           :spacex.launch/launch-year               "2019",
                                           :spacex.launch.fairings/recovered        true,
                                           :spacex.launch.links/youtube-id          "fZh82-WcCuo",
                                           :spacex.launch/launch-success            true,
                                           :spacex.launch/tbd                       false,
                                           :spacex.launch/tentative-max-precision   "hour",
                                           :spacex.launch.fairings/reused           false,
                                           :spacex.launch/ships                     ["GOMSTREE"
                                                                                     "GONAVIGATOR"],
                                           :spacex.launch.first-stage/cores         [{:spacex.core/reused          true,
                                                                                      :spacex.core/core-serial     "B1047",
                                                                                      :spacex.core/land-success    nil,
                                                                                      :spacex.core/flight          3,
                                                                                      :spacex.core/gridfins        false,
                                                                                      :spacex.core/landing-type    nil,
                                                                                      :spacex.core/block           5,
                                                                                      :spacex.core/legs            false,
                                                                                      :spacex.core/landing-intent  false,
                                                                                      :spacex.core/landing-vehicle nil}],
                                           :spacex.launch/launch-date-utc           "2019-08-06T22:52:00.000Z",
                                           :spacex.launch.links/reddit-media        "https://www.reddit.com/r/spacex/comments/cmppne/rspacex_amos17_media_thread_videos_images_gifs",
                                           :spacex.rocket/rocket-name               "Falcon 9",
                                           :spacex.launch.links/reddit-recovery     nil,
                                           :spacex.launch.links/mission-patch-small "https://images2.imgbox.com/f1/4a/WAkSmKfY_o.png",
                                           :spacex.launch/timeline                  nil,
                                           :spacex.launch/static-fire-date-unix     1564617600,
                                           :spacex.launch.links/reddit-campaign     "https://www.reddit.com/r/spacex/comments/cjaawx/amos17_launch_campaign_thread",
                                           :spacex.launch-pad/site-name             "CCAFS SLC 40",
                                           :spacex.launch.second-stage/payloads     [{:spacex.payload.orbit-params/mean-motion        nil,
                                                                                      :spacex.payload/payload-id                      "Amos-17",
                                                                                      :spacex.payload.orbit-params/period-min         nil,
                                                                                      :spacex.payload/manufacturer                    "Boeing Satellite Systems",
                                                                                      :spacex.payload.orbit-params/raan               nil,
                                                                                      :spacex.payload.orbit-params/epoch              nil,
                                                                                      :spacex.payload.orbit-params/lifespan-years     15,
                                                                                      :spacex.payload.orbit-params/regime             "geostationary",
                                                                                      :spacex.payload/reused                          false,
                                                                                      :spacex.payload.orbit-params/inclination-deg    nil,
                                                                                      :spacex.payload.orbit-params/periapsis-km       nil,
                                                                                      :spacex.payload/payload-mass-kg                 6500,
                                                                                      :spacex.payload.orbit-params/eccentricity       nil,
                                                                                      :spacex.payload.orbit-params/mean-anomaly       nil,
                                                                                      :spacex.payload/payload-type                    "Satellite",
                                                                                      :spacex.payload.orbit-params/reference-system   "geocentric",
                                                                                      :spacex.payload.orbit-params/apoapsis-km        nil,
                                                                                      :spacex.payload/orbit                           "GTO",
                                                                                      :spacex.payload/norad-id                        [],
                                                                                      :spacex.payload.orbit-params/longitude          17,
                                                                                      :spacex.payload/customers                       ["Spacecom"],
                                                                                      :spacex.payload.orbit-params/arg-of-pericenter  nil,
                                                                                      :spacex.payload/nationality                     "Israel",
                                                                                      :spacex.payload/payload-mass-lbs                14330.05,
                                                                                      :spacex.payload.orbit-params/semi-major-axis-km nil}],
                                           :spacex.launch/launch-date-local         "2019-08-06T18:52:00-04:00",
                                           :spacex.rocket/rocket-id                 "falcon9",
                                           :spacex.launch.fairings/recovery-attempt true,
                                           :spacex.launch.links/article-link        "https://spaceflightnow.com/2019/08/07/spacex-launches-israeli-owned-telecom-satellite/",
                                           :spacex.launch.links/flickr-images       ["https://live.staticflickr.com/65535/48478269312_58dd3dc446_o.jpg"
                                                                                     "https://live.staticflickr.com/65535/48478269747_353dcb2e62_o.jpg"
                                                                                     "https://live.staticflickr.com/65535/48478119901_2de0441026_o.jpg"
                                                                                     "https://live.staticflickr.com/65535/48478120646_ab72c2c6c3_o.jpg"
                                                                                     "https://live.staticflickr.com/65535/48478120031_5aae1f6131_o.jpg"
                                                                                     "https://live.staticflickr.com/65535/48478269442_08479bed36_o.jpg"],
                                           :spacex.launch/static-fire-date-utc      "2019-08-01T00:00:00.000Z",
                                           :spacex.launch/launch-date-unix          1565131920,
                                           :spacex.launch.telemetry/flight-club     nil,
                                           :spacex.launch.links/reddit-launch       "https://www.reddit.com/r/spacex/comments/cmedgn/rspacex_amos17_official_launch_discussion_updates",
                                           :spacex.launch/mission-name              "Amos-17",
                                           :spacex.launch.links/presskit            "https://www.spacex.com/sites/spacex/files/amos-17_mission_press_kit_8_6_2019.pdf",
                                           :spacex.launch/crew                      nil,
                                           :spacex.launch/is-tentative              false,
                                           :spacex.launch/upcoming                  false,
                                           :spacex.launch.second-stage/block        5}})

